version: "3.0"
services: 
    # DB: Google Cloud SQL (MySQL 8.0)
    # DB_URL: Automatically supplied by the system env $DATABASE_URL
    # Frontend: nuxt generate -> firebase static
    back:
        image: $REGISTRY_URL/app_image:latest
        environment:
         - SPROCKETS_CACHE=/cache
         - RAILS_ENV=production
         - DATABASE_IP=$DATABASE_IP
         - SECRET_KEY_BASE=$SECRET_KEY_BASE
        build: rails_app
        command: bash -c "bundle exec rails db:setup && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        container_name: app_container
        ports: 
            - 80:3000
        volumes: 
            - gem_data:/usr/local/bundle
            - cache:/cache
        labels:
            kompose.service.type: LoadBalancer
            kompose.image-pull-policy: "Always"
            
volumes: 
    gem_data:
    cache: