version: "3.0"
services: 
    db:
        container_name: db_container
        build: ./mysql
        image: db_image
        volumes: 
            - mysql_data:/var/lib/mysql
    back:
        build: rails_app
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        image: app_image
        container_name: app_container
        ports: 
            - 3000:3000
        volumes: 
            - ./rails_app:/rails_app
            - gem_data:/usr/local/bundle
        depends_on: 
            - db
    front:
        container_name: front
        build: 
            context: ./nuxt
            dockerfile: Dockerfile
        ports: 
            - 8080:3000
        volumes: 
            - ./nuxt/src:/src:cached
            - node_modules_data:/src/app/node_modules
        tty: true
        stdin_open: true
        environment: 
            - CHOKIDAR_USEPOLLING=true

volumes: 
    gem_data:
    mysql_data:
    node_modules_data:


