apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "34"
    kompose.cmd: kompose convert -f ../docker-compose-prod-complete.yml
    kompose.image-pull-policy: Always
    kompose.service.type: LoadBalancer
    kompose.version: 1.19.0 (f63a961c)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose convert -f ../docker-compose-prod-complete.yml","kompose.image-pull-policy":"Always","kompose.service.type":"LoadBalancer","kompose.version":"1.19.0 (f63a961c)"},"creationTimestamp":null,"labels":{"io.kompose.service":"back"},"name":"back","namespace":"default"},"spec":{"replicas":1,"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose convert -f ../docker-compose-prod-complete.yml","kompose.image-pull-policy":"Always","kompose.service.type":"LoadBalancer","kompose.version":"1.19.0 (f63a961c)"},"creationTimestamp":null,"labels":{"io.kompose.service":"back"}},"spec":{"containers":[{"args":["bash","-c","bundle exec rails db:setup \u0026\u0026 rm -f tmp/pids/server.pid \u0026\u0026 bundle exec rails s -p 3000 -b '0.0.0.0'"],"env":[{"name":"DATABASE_IP","value":"10.123.32.3"},{"name":"DISABLE_DATABASE_ENVIRONMENT_CHECK","value":"1"},{"name":"RAILS_ENV","value":"production"},{"name":"SECRET_KEY_BASE","value":"<redacted>"},{"name":"SPROCKETS_CACHE","value":"/cache"}],"image":"asia.gcr.io/incomi/app_image:latest","imagePullPolicy":"Always","name":"app-container","ports":[{"containerPort":3000}],"resources":{},"volumeMounts":[{"mountPath":"/usr/local/bundle","name":"gem-data"},{"mountPath":"/cache","name":"cache"}]}],"restartPolicy":"Always","volumes":[{"name":"gem-data","persistentVolumeClaim":{"claimName":"gem-data"}},{"name":"cache","persistentVolumeClaim":{"claimName":"cache"}}]}}},"status":{}}
  creationTimestamp: "2020-09-23T09:11:30Z"
  generation: 35
  labels:
    io.kompose.service: back
  name: back
  namespace: default
  resourceVersion: "1354587"
  selfLink: /apis/apps/v1/namespaces/default/deployments/back
  uid: 84840176-2457-40fa-8451-0420b9e82584
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: back
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-prod-complete.yml
        kompose.image-pull-policy: Always
        kompose.service.type: LoadBalancer
        kompose.version: 1.19.0 (f63a961c)
        kubectl.kubernetes.io/restartedAt: "2020-09-25T06:12:48Z"
      creationTimestamp: null
      labels:
        io.kompose.service: back
    spec:
      containers:
      - args:
        - bash
        - -c
        - bundle exec rails db:setup && rm -f tmp/pids/server.pid && bundle exec rails
          s -p 3000 -b '0.0.0.0'
        env:
        - name: DATABASE_IP
          value: 10.123.32.3
        - name: DISABLE_DATABASE_ENVIRONMENT_CHECK
          value: "1"
        - name: RAILS_ENV
          value: production
        - name: SECRET_KEY_BASE
          value: <redacted>
        - name: SPROCKETS_CACHE
          value: /cache
        image: asia.gcr.io/incomi/app_image:latest
        imagePullPolicy: Always
        name: app-container
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/bundle
          name: gem-data
        - mountPath: /cache
          name: cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gem-data
        persistentVolumeClaim:
          claimName: gem-data
      - name: cache
        persistentVolumeClaim:
          claimName: cache
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-25T06:13:28Z"
    lastUpdateTime: "2020-09-25T06:13:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 35
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
