apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"io.kompose.service":"cache"},"name":"cache","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Mi"}}},"status":{}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2020-09-21T18:29:36Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    io.kompose.service: cache
  name: cache
  namespace: default
  resourceVersion: "40720"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/cache
  uid: 2eea2769-1b4e-4a96-b6d5-6118c9cface1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-2eea2769-1b4e-4a96-b6d5-6118c9cface1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
