apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"io.kompose.service":"gem-data"},"name":"gem-data","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Mi"}}},"status":{}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2020-09-21T18:29:36Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    io.kompose.service: gem-data
  name: gem-data
  namespace: default
  resourceVersion: "40724"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/gem-data
  uid: 131be485-938f-45fa-a629-f162d663c98b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-131be485-938f-45fa-a629-f162d663c98b
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
